// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Icon:mdi:arrowUpDown': typeof import('~icons/mdi/arrow-up-down')['default']
    'Icon:mdi:drop': typeof import('~icons/mdi/drop')['default']
    'Icon:mdi:weatherCloudy': typeof import('~icons/mdi/weather-cloudy')['default']
    'Icon:mdi:weatherFog': typeof import('~icons/mdi/weather-fog')['default']
    'Icon:mdi:weatherLightning': typeof import('~icons/mdi/weather-lightning')['default']
    'Icon:mdi:weatherNight': typeof import('~icons/mdi/weather-night')['default']
    'Icon:mdi:weatherNightPartlyCloudy': typeof import('~icons/mdi/weather-night-partly-cloudy')['default']
    'Icon:mdi:weatherPartlyCloudy': typeof import('~icons/mdi/weather-partly-cloudy')['default']
    'Icon:mdi:weatherPouring': typeof import('~icons/mdi/weather-pouring')['default']
    'Icon:mdi:weatherRainy': typeof import('~icons/mdi/weather-rainy')['default']
    'Icon:mdi:weatherSnowy': typeof import('~icons/mdi/weather-snowy')['default']
    'Icon:mdi:weatherSunny': typeof import('~icons/mdi/weather-sunny')['default']
    'Icon:mdi:weatherSunsetDown': typeof import('~icons/mdi/weather-sunset-down')['default']
    'Icon:mdi:weatherSunsetUp': typeof import('~icons/mdi/weather-sunset-up')['default']
    'IconAkarIcons:location': typeof import('~icons/akar-icons/location')['default']
    'IconIc:baselineCheck': typeof import('~icons/ic/baseline-check')['default']
    WeatherCard: typeof import('./src/components/WeatherCard.vue')['default']
    WeatherIcon: typeof import('./src/components/WeatherIcon.vue')['default']
  }
}

export { }
